### ISSUE TITLE
1 - refactoring code by 'Team lead' comment HW8

### ISSUE THREAD

**Issue by AlexanderSibirko** [AlexanderSibirko/js_frontend#1]
hw8.html
[Алексей Кадочников・Преподаватель](https://gb.ru/users/teachers/138173)
Добрый день

        (target.classList.contains(searchClass)) ? 
        console.log(`Класс ${searchClass} присутствует в элементе ${target.tagName}`) : 
        console.log(`Класс ${searchClass} отсутствует в элементе ${target.tagName}`);
тут можно было тернарный прям внутри консоль лога и только на слово присутствует и отсутствует

**Comment by TorikSAn** [comment]
Ок принял в работу
